language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
before_install:
  - gem install bundler
gemfile:
  - .gemfiles/Gemfile.mongoid3
  - .gemfiles/Gemfile.mongoid4
  - .gemfiles/Gemfile.mongoid4_rails41
  - .gemfiles/Gemfile.mongoid4_rails42
  - .gemfiles/Gemfile.mongoid5_rails4
  - .gemfiles/Gemfile.mongoid_head
matrix:
  allow_failures:
    - gemfile: .gemfiles/Gemfile.mongoid_head
  include:
    - rvm: 2.3.1
      gemfile: .gemfiles/Gemfile.mongoid6_rails5
notifications:
  recipients:
    - jerry.clinesmith@koanhealth.com
services:
  - mongodb

